<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<TrimMode>partial</TrimMode>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\**"/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.20" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
		<PackageReference Include="WebView.Avalonia.Desktop" Version="11.0.0.1"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Auth0Avalonia\Auth0Avalonia.csproj"/>
	</ItemGroup>
</Project>
