<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>library</OutputType>
		<RootNamespace>Auth0Avalonia</RootNamespace>
		<AssemblyName>Auth0Avalonia</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>default</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Auth0.OidcClient.Core" Version="4.2.0" />
		<PackageReference Include="WebView.Avalonia" Version="11.0.0.1"/>
	</ItemGroup>
</Project>